import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedexpendinfowidget/generated/GeneratedIOSStatusBarBlackWidget4.dart';
import 'package:flutterapp/deckinfoapp/generatedexpendinfowidget/generated/GeneratedGroup62Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedexpendinfowidget/generated/GeneratedGroup65Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedexpendinfowidget/generated/GeneratedGroup61Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedexpendinfowidget/generated/GeneratedLine84Widget.dart';

/* Frame Expend Info
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedExpendInfoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 73.0,
                child: GeneratedIOSStatusBarBlackWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 122.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 47.0,
                child: GeneratedGroup62Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedGroup61Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 301.0,
                child: GeneratedGroup65Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 1.0,
                child: GeneratedLine84Widget(),
              )
            ]),
      ),
    ));
  }
}
