import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedaboutteamwidget/generated/GeneratedGroup53Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedaboutteamwidget/generated/GeneratedIOSStatusBarBlackWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedaboutteamwidget/generated/GeneratedGroup69Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedaboutteamwidget/generated/GeneratedInputSearchWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedaboutteamwidget/generated/GeneratedGroup68Widget.dart';

/* Frame About Team
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAboutTeamWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 219.0,
                right: 13.0,
                bottom: null,
                width: null,
                height: 247.00003051757812,
                child: GeneratedGroup68Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 485.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 263.0000305175781,
                child: GeneratedGroup69Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedGroup53Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 127.0,
                right: 15.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget(),
              )
            ]),
      ),
    ));
  }
}
