import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedIOSStatusBarBlackWidget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedInputTextWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedDECKINFOFinal2Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedGreydownarrowiconpng12Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedRectangle240Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedSIGNINWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedLine81Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedInputTextWidget2.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedLine82Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedForgotyourpasswordWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedInputTextWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedsigninpagewidget/generated/GeneratedButtonPrimaryWidget.dart';

/* Frame sign in page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSigninpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 73.0,
                child: GeneratedIOSStatusBarBlackWidget3(),
              ),
              Positioned(
                left: -34.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 409.0,
                height: 46.0,
                child: GeneratedRectangle240Widget(),
              ),
              Positioned(
                left: 188.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 46.0,
                height: 1.0,
                child: GeneratedLine81Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 3.0,
                child: GeneratedLine82Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 23.0,
                child: GeneratedSIGNINWidget(),
              ),
              Positioned(
                left: 229.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 23.0,
                child: GeneratedSIGNUPWidget(),
              ),
              Positioned(
                left: 74.0,
                top: 141.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 252.0,
                child: GeneratedDECKINFOFinal2Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 349.0,
                right: 13.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 479.0,
                right: 13.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: null,
                right: 19.0,
                bottom: 164.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 247.0,
                width: 180.0,
                height: 21.0,
                child: TransformHelper.translate(
                    x: -1.50,
                    y: 0.00,
                    z: 0,
                    child: GeneratedForgotyourpasswordWidget()),
              ),
              Positioned(
                left: 19.0,
                top: 414.0,
                right: 13.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget2(),
              ),
              Positioned(
                left: 314.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 16.0,
                child: GeneratedGreydownarrowiconpng12Widget(),
              )
            ]),
      ),
    ));
  }
}
