import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedGroup72Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedGroup60Widget1.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedInputSearchWidget2.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedRectangle244Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedPageHeaderWidget5.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedRectangle246Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedUntitleddesign181Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedGroup71Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedRectangle243Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedUntitleddesign82Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedRectangle245Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedRectangle242Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedUntitleddesign211Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedIOSStatusBarBlackWidget8.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedtideinfopagewidget/generated/GeneratedUntitleddesign201Widget.dart';

/* Frame Tide Info. page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTideInfopageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 36.0,
                child: GeneratedPageHeaderWidget5(),
              ),
              Positioned(
                left: 18.0,
                top: 128.0,
                right: 14.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedGroup60Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 270.0,
                child: GeneratedRectangle242Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 87.0,
                child: GeneratedRectangle243Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 22.0,
                child: GeneratedRectangle244Widget(),
              ),
              Positioned(
                left: 334.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 26.0,
                height: 22.0,
                child: GeneratedRectangle245Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 316.0,
                height: 279.0,
                child: GeneratedRectangle246Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 256.0,
                height: 244.0,
                child: GeneratedGroup70Widget(),
              ),
              Positioned(
                left: 82.0,
                top: null,
                right: null,
                bottom: null,
                width: 152.0,
                height: 342.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 176.00, z: 0, child: GeneratedGroup71Widget()),
              ),
              Positioned(
                left: 66.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 42.0,
                child: GeneratedUntitleddesign82Widget(),
              ),
              Positioned(
                left: 33.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 52.0,
                child: GeneratedUntitleddesign181Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 219.0,
                child: GeneratedGroup72Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 56.0,
                height: 54.0,
                child: GeneratedUntitleddesign201Widget(),
              ),
              Positioned(
                left: 281.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 65.0,
                child: GeneratedUntitleddesign211Widget(),
              )
            ]),
      ),
    ));
  }
}
