import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedUntitleddesign121Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedUntitleddesign131Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedWeatherInformationWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedGroup59Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedUntitleddesign161Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedHINameWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedGroup54Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedUntitleddesign151Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedIOSStatusBarBlackWidget2.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedTeamInformationWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedSeawaveTideInformationWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedhomepagewidget/generated/GeneratedExpenditureInformationWidget.dart';

/* Frame Home Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedUntitleddesign121Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget2(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: 493.0,
                width: 151.0,
                height: 38.0,
                child: TransformHelper.translate(
                    x: -76.00, y: 0.00, z: 0, child: GeneratedHINameWidget()),
              ),
              Positioned(
                left: 13.0,
                top: 68.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 277.0,
                child: GeneratedGroup54Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 316.0,
                child: GeneratedGroup59Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 316.0,
                child: GeneratedGroup60Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 424.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 78.0,
                child: GeneratedUntitleddesign131Widget(),
              ),
              Positioned(
                left: 58.0,
                top: null,
                right: null,
                bottom: null,
                width: 95.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 117.50,
                    z: 0,
                    child: GeneratedTeamInformationWidget()),
              ),
              Positioned(
                left: 228.0,
                top: null,
                right: null,
                bottom: null,
                width: 92.0,
                height: 40.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 120.00,
                    z: 0,
                    child: GeneratedWeatherInformationWidget()),
              ),
              Positioned(
                left: 47.0,
                top: null,
                right: null,
                bottom: null,
                width: 114.0,
                height: 40.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 290.00,
                    z: 0,
                    child: GeneratedSeawaveTideInformationWidget()),
              ),
              Positioned(
                left: 228.0,
                top: null,
                right: null,
                bottom: null,
                width: 99.0,
                height: 43.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 291.50,
                    z: 0,
                    child: GeneratedExpenditureInformationWidget()),
              ),
              Positioned(
                left: 62.0,
                top: 586.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 80.0,
                child: GeneratedUntitleddesign151Widget(),
              ),
              Positioned(
                left: 241.0,
                top: 602.0,
                right: null,
                bottom: null,
                width: 60.0,
                height: 54.0,
                child: GeneratedUntitleddesign161Widget(),
              )
            ]),
      ),
    ));
  }
}
