import 'package:flutter/material.dart';

/* Rectangle Untitled design 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUntitleddesign1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 239.0,
      height: 322.0,
    ));
  }
}
