import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget6.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedIOSStatusBarBlackWidget5.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget5.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget9.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget8.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedButtonPrimaryWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget3.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedDECKINFOFinal2Widget1.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedGreydownarrowiconpng11Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedsignuppagewidget/generated/GeneratedInputTextWidget7.dart';

/* Frame  signup page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedsignuppageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 73.0,
                child: GeneratedIOSStatusBarBlackWidget5(),
              ),
              Positioned(
                left: -1.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 47.0,
                child: GeneratedGroup41Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 156.0,
                child: GeneratedDECKINFOFinal2Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 263.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget3(),
              ),
              Positioned(
                left: 16.0,
                top: 329.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget4(),
              ),
              Positioned(
                left: 16.0,
                top: 465.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 527.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 397.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 589.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 651.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputTextWidget9(),
              ),
              Positioned(
                left: 16.0,
                top: null,
                right: 16.0,
                bottom: 36.0,
                width: null,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget1(),
              ),
              Positioned(
                left: 310.0,
                top: 546.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 16.0,
                child: GeneratedGreydownarrowiconpng11Widget(),
              )
            ]),
      ),
    ));
  }
}
