import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo1widget/generated/GeneratedNameBioWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo1widget/generated/GeneratedSegmentedControlRightWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo1widget/generated/GeneratedIOSStatusBarBlackWidget12.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo1widget/generated/GeneratedGroup70Widget3.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo1widget/generated/GeneratedIOSStatusBarWhiteWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo1widget/generated/GeneratedGroup70Widget2.dart';

/* Frame Person info 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPersoninfo1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget1(),
              ),
              Positioned(
                left: 91.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 36.0,
                child: GeneratedNameBioWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 201.0,
                right: 7.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedSegmentedControlRightWidget(),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget12(),
              ),
              Positioned(
                left: 15.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedGroup70Widget2(),
              ),
              Positioned(
                left: 25.0,
                top: 284.0,
                right: 5.0,
                bottom: null,
                width: null,
                height: 247.00003051757812,
                child: GeneratedGroup70Widget3(),
              )
            ]),
      ),
    ));
  }
}
