import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo2widget/generated/GeneratedIOSStatusBarBlackWidget14.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo2widget/generated/GeneratedIOSStatusBarWhiteWidget2.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo2widget/generated/GeneratedDownload71Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo2widget/generated/GeneratedSegmentedControlRightWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo2widget/generated/GeneratedGroup70Widget4.dart';
import 'package:flutterapp/deckinfoapp/generatedpersoninfo2widget/generated/GeneratedNameBioWidget2.dart';

/* Frame Person info 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPersoninfo2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget2(),
              ),
              Positioned(
                left: 91.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 36.0,
                child: GeneratedNameBioWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 201.0,
                right: 7.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedSegmentedControlRightWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: -3.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget14(),
              ),
              Positioned(
                left: 15.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedGroup70Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 328.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 313.0,
                child: GeneratedDownload71Widget(),
              )
            ]),
      ),
    ));
  }
}
