import 'package:flutter/material.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup42Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedPorbandarWidget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedLine83Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGreenGradientsBeverages916StoryAd1Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup49Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedIOSStatusBarBlackWidget7.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedInputSearchWidget1.dart';
import 'package:flutterapp/deckinfoapp/generatedweatherinfopagewidget/generated/GeneratedGroup45Widget.dart';

/* Frame Weather Info. page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWeatherInfopageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(25.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(25.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedGreenGradientsBeverages916StoryAd1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget7(),
              ),
              Positioned(
                left: 18.0,
                top: 128.0,
                right: 14.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: GeneratedInputSearchWidget1(),
              ),
              Positioned(
                left: 112.0,
                top: null,
                right: null,
                bottom: null,
                width: 157.0,
                height: 41.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: -165.50,
                    z: 0,
                    child: GeneratedPorbandarWidget()),
              ),
              Positioned(
                left: 26.0,
                top: null,
                right: null,
                bottom: null,
                width: 320.0,
                height: 17.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 238.50, z: 0, child: GeneratedGroup44Widget()),
              ),
              Positioned(
                left: 21.0,
                top: null,
                right: null,
                bottom: null,
                width: 40.0,
                height: 101.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 309.50, z: 0, child: GeneratedGroup45Widget()),
              ),
              Positioned(
                left: 278.0,
                top: null,
                right: null,
                bottom: null,
                width: 55.0,
                height: 17.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 267.50, z: 0, child: GeneratedGroup48Widget()),
              ),
              Positioned(
                left: 278.0,
                top: null,
                right: null,
                bottom: null,
                width: 56.0,
                height: 17.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 296.50, z: 0, child: GeneratedGroup49Widget()),
              ),
              Positioned(
                left: 278.0,
                top: null,
                right: null,
                bottom: null,
                width: 56.0,
                height: 17.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 322.50, z: 0, child: GeneratedGroup50Widget()),
              ),
              Positioned(
                left: 278.0,
                top: null,
                right: null,
                bottom: null,
                width: 56.0,
                height: 17.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 351.50, z: 0, child: GeneratedGroup51Widget()),
              ),
              Positioned(
                left: 97.0,
                top: null,
                right: null,
                bottom: null,
                width: 31.0,
                height: 104.0,
                child: TransformHelper.translate(
                    x: 0.00, y: 311.00, z: 0, child: GeneratedGroup46Widget()),
              ),
              Positioned(
                left: 136.0,
                top: null,
                right: null,
                bottom: null,
                width: 133.0,
                height: 129.0,
                child: TransformHelper.translate(
                    x: 0.00, y: -47.50, z: 0, child: GeneratedGroup42Widget()),
              ),
              Positioned(
                left: 21.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 327.0,
                height: 1.0,
                child: GeneratedLine83Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 45.0,
                child: GeneratedGroup52Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 276.0,
                child: GeneratedGroup47Widget(),
              )
            ]),
      ),
    ));
  }
}
